server.port: 8080

spring:
  thymeleaf:
    cache: false
    prefix: file:/app/templates/
  web:
    resources:
      static-locations: file:/app/static/
  datasource:
    url: jdbc:postgresql://db:5432/card_generator_db
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    validationQuery: SELECT 1
  batch.jdbc.initialize-schema: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate.jdbc.lob.non_contextual_creation: true
jwt:
  expiration: 108_000_000 # 30 days in millis
logging.level.org:
  springframework: DEBUG
  springframework.boot.autoconfigure.logging.ConditionEvaluationReportLogger: OFF
